### ISSUE TITLE
!help -> (node:151628) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function  

### ISSUE THREAD

**Issue by GregorKeks** [SCNetwork/CustomDCBot#17]
Hello,
I have installed the bot on an Ubuntu 20.04 lts server. NodeJS and npm are on the latest version. All IDs and tokens are registered. The bot is on my server and I can use single modules like mute and ban. But as soon as I enter !help the following error message appears.

(node:151628) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/CustomDCBot-main/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.addFields (/home/CustomDCBot-main/node_modules/discord.js/src/structures/MessageEmbed.js:266:42)
    at MessageEmbed.addField (/home/CustomDCBot-main/node_modules/discord.js/src/structures/MessageEmbed.js:257:17)
    at Object.module.exports.run (/home/CustomDCBot-main/src/commands/help.js:23:23)
    at Object.exports.run (/home/CustomDCBot-main/src/events/message.js:20:17)
    at Client.client.on.args (/home/CustomDCBot-main/main.js:164:69)
    at Client.emit (events.js:198:13)
    at MessageCreateAction.handle (/home/CustomDCBot-main/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/CustomDCBot-main/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/CustomDCBot-main/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
(node:151628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:151628) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Is there a way to fix this?

**Comment by SCDerox** [comment]
Hi,
thanks so much for your issue. Unfortunately I can't reproduce your error on my system. Have you changed any source-files? 
Also it would be great if you could share your `modules.json` and your `strings.json`.
Thank you!

**Comment by GregorKeks** [comment]
No and yes?
I have set it for test purposes, but nothing more.

[modules.txt](https://github.com/SCNetwork/CustomDCBot/files/6696462/modules.txt)
[strings.txt](https://github.com/SCNetwork/CustomDCBot/files/6696464/strings.txt)

**Comment by SCDerox** [comment]
Hey, thanks again for your reply. I have imported your configuration and can't reproduce your error on my system. Are you sure you are running the newest node.js version? Could you run `node -v`and check?

**Comment by GregorKeks** [comment]
My node version ist 14.17.1

**Comment by SCDerox** [comment]
Okay, that should be fine as I have the same version on our servers. I can't really help you as I can't reproduce this behavior.
You could try sending me all your configuration files so I can replicate your system. (Please censor your token)

**Comment by GregorKeks** [comment]
[CustomDCBot-main.zip](https://github.com/SCNetwork/CustomDCBot/files/6696714/CustomDCBot-main.zip)
