### ISSUE TITLE
i need help !help is dont work

### ISSUE THREAD

**Issue by amorking1996** [SCNetwork/CustomDCBot#22]
[BOT] Client logged in as GhostRPNew#3510 and is now online!
[INFO] Checking configs...
[INFO] Done with checking.
[BOT] The bot initiated successfully and is now listening to commands.
(node:303643) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not afunction
    at Function.normalizeFields (/home/DCBot/node_modules/discord.js/src/structres/MessageEmbed.js:450:8)
    at MessageEmbed.addFields (/home/DCBot/node_modules/discord.js/src/structurs/MessageEmbed.js:266:42)
    at MessageEmbed.addField (/home/DCBot/node_modules/discord.js/src/structure/MessageEmbed.js:257:17)
    at Object.module.exports.run (/home/DCBot/src/commands/help.js:25:23)
    at Object.exports.run (/home/DCBot/src/events/message.js:20:17)
    at Client.client.on.args (/home/DCBot/main.js:164:69)
    at Client.emit (events.js:198:13)
    at MessageCreateAction.handle (/home/DCBot/node_modules/discord.js/src/cliet/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/DCBot/node_modules/discrd.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/DCBot/node_modules/discord.js/src/cient/websocket/WebSocketManager.js:384:31)
(node:303643) UnhandledPromiseRejectionWarning: Unhandled promise rejection. Ths error originated either by throwing inside of an async function without a cath block, or by rejecting a promise which was not handled with .catch(). (rejecton id: 1)
(node:303643) [DEP0018] DeprecationWarning: Unhandled promise rejections are derecated. In the future, promise rejections that are not handled will terminate he Node.js process with a non-zero exit code.

**Comment by SCDerox** [comment]
Hi, thanks for creating an issue. Please provide your whole log and explain, what you are trying to do, so I can actually help you.

**Comment by amorking1996** [comment]
That's the whole protocol I want! Use help but when I do this, this error occurs

**Comment by SCDerox** [comment]
Please send the whole log (not just the error), so I can help you - this is not the whole log, it usually has a lot more detailed information in it.
Please also send your node version and on which OS you are running the bot.

**Comment by amorking1996** [comment]
Version Ubuntu 20.04

root@v46821:/home/DCBot# npm start

> customdcbot@1.0.0 start /home/DCBot
> node main.js

[MODULE] Module admin-tools is disabled
[MODULE] Module auto-publisher is disabled
[MODULE] Module auto-react is disabled
[MODULE] Module betterstatus is disabled
[MODULE] Module birthday is disabled
[MODULE] Module giveaways is disabled
[MODULE] Module levels is disabled
[MODULE] Module moderation is disabled
[MODULE] Module partner-list is disabled
[MODULE] Module ping-on-vc-join is disabled
[MODULE] Module reaction-role is disabled
[MODULE] Module serverinfo is disabled
[MODULE] Module suggestions is disabled
[MODULE] Module welcomer is disabled
[COMMANDS] Loaded ./src/commands/help.js
[COMMANDS] Loaded ./src/commands/module.js
[EVENTS] Loaded ./src/events/botReady.js
[EVENTS] Loaded ./src/events/ready.js
[EVENTS] Loaded ./src/events/message.js
[DB] Synced db
[BOT] Client logged in as GhostRPNew#3510 and is now online!
[INFO] Checking configs...
[INFO] Done with checking.
[BOT] The bot initiated successfully and is now listening to commands.
(node:303709) UnhandledPromiseRejectionWarning: TypeError: fields.flat is not a function
    at Function.normalizeFields (/home/DCBot/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.addFields (/home/DCBot/node_modules/discord.js/src/structures/MessageEmbed.js:266:42)
    at MessageEmbed.addField (/home/DCBot/node_modules/discord.js/src/structures/MessageEmbed.js:257:17)
    at Object.module.exports.run (/home/DCBot/src/commands/help.js:25:23)
    at Object.exports.run (/home/DCBot/src/events/message.js:20:17)
    at Client.client.on.args (/home/DCBot/main.js:164:69)
    at Client.emit (events.js:198:13)
    at MessageCreateAction.handle (/home/DCBot/node_modules/discord.js/src/client/actions/MessageCreate.js:31:14)
    at Object.module.exports [as MESSAGE_CREATE] (/home/DCBot/node_modules/discord.js/src/client/websocket/handlers/MESSAGE_CREATE.js:4:32)
    at WebSocketManager.handlePacket (/home/DCBot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:384:31)
(node:303709) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:303709) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by amorking1996** [comment]
isit right?

**Comment by SCDerox** [comment]
Okay, thank you. What node version are you running the bot on?

**Comment by amorking1996** [comment]
10

**Comment by amorking1996** [comment]
root@v46821:/home/DCBot# node --version
v10.19.0
root@v46821:/home/DCBot#

**Comment by SCDerox** [comment]
Sorry, but you need to use at least node v12 as per the [discord.js docs](https://discord.js.org/#:~:text=the%20Discord%20API-,Installation,-Node.js%2012.0.0).

**Comment by amorking1996** [comment]
okay im installing v12 one sec

**Comment by amorking1996** [comment]
okay its works ths for helping
