### ISSUE TITLE
I can't use the help and reload command since I updated to V2.1.0

### ISSUE THREAD

**Issue by jateute** [SCNetwork/CustomDCBot#44]
Since I updated my bot to V2.10, I can't use the help and reload command ( I hadn't tried any other commands). This is the Log:
```> customdcbot@2.1.0 start
> node main.js

[2022-01-04T16:12:34.460] [INFO] default - CustomBot v2 (https://github.com/SCNetwork/CustomDCBot) - Log-Level: DEBUG
[2022-01-04T16:12:39.623] [DEBUG] default - Loaded database model /src/models/ChannelLock.js
[2022-01-04T16:12:39.783] [DEBUG] default - Loaded database model /src/models/DatabaseSchemeVersion.js
[2022-01-04T16:12:39.915] [DEBUG] default - Module admin-tools is disabled
[2022-01-04T16:12:39.995] [DEBUG] default - Module auto-publisher is disabled
[2022-01-04T16:12:40.032] [DEBUG] default - Module auto-react is disabled
[2022-01-04T16:12:40.091] [DEBUG] default - Module betterstatus is disabled
[2022-01-04T16:12:40.138] [DEBUG] default - Module birthday is disabled
[2022-01-04T16:12:40.195] [DEBUG] default - Loading module economy-system
[2022-01-04T16:12:40.331] [DEBUG] default - Loaded database model ./modules/economy-system/models/cooldowns.js
[2022-01-04T16:12:40.466] [DEBUG] default - Loaded database model ./modules/economy-system/models/shop.js
[2022-01-04T16:12:40.505] [DEBUG] default - Loaded database model ./modules/economy-system/models/user.js
[2022-01-04T16:12:40.549] [DEBUG] default - Module giveaways is disabled
[2022-01-04T16:12:40.622] [DEBUG] default - Module levels is disabled
[2022-01-04T16:12:40.695] [DEBUG] default - Module partner-list is disabled
[2022-01-04T16:12:40.723] [DEBUG] default - Module ping-on-vc-join is disabled
[2022-01-04T16:12:40.735] [DEBUG] default - Module serverinfo is disabled
[2022-01-04T16:12:40.770] [DEBUG] default - Module suggestions is disabled
[2022-01-04T16:12:40.787] [DEBUG] default - Module twitch-notifications is disabled
[2022-01-04T16:12:40.822] [DEBUG] default - Module welcomer is disabled
[2022-01-04T16:12:41.970] [DEBUG] default - Loaded events ./modules/economy-system/events/botReady.js
[2022-01-04T16:12:42.054] [DEBUG] default - Loaded events ./modules/economy-system/events/messageCreate.js
[2022-01-04T16:12:42.152] [DEBUG] default - Loaded events ./src/events/botReady.js
[2022-01-04T16:12:42.208] [DEBUG] default - Loaded events ./src/events/interactionCreate.js
[2022-01-04T16:12:42.300] [DEBUG] default - Loaded events ./src/events/messageCreate.js
[2022-01-04T16:12:42.396] [DEBUG] default - Loaded events ./src/events/ready.js
[2022-01-04T16:12:43.439] [INFO] default - Synced database
[2022-01-04T16:12:43.542] [DEBUG] default - Loaded command ./src/message-commands/help.js
[2022-01-04T16:12:45.885] [INFO] default - Bot logged in as TestBot155154184#1745 and is now online.
[2022-01-04T16:12:45.991] [DEBUG] default - Loaded API-Action help in /src/cli.js
[2022-01-04T16:12:46.073] [DEBUG] default - Loaded API-Action license in /src/cli.js
[2022-01-04T16:12:46.152] [DEBUG] default - Loaded API-Action reload in /src/cli.js
[2022-01-04T16:12:46.246] [INFO] default - Checking configurations...
[2022-01-04T16:12:46.656] [INFO] default - Done with checking.
[2022-01-04T16:12:47.932] [INFO] default - Application commands are up to date - no syncing required
[2022-01-04T16:12:47.942] [INFO] default - The bot initiated successfully and is now listening to commands
> TypeError: interaction.isAutocomplete is not a function
    at Object.module.exports.run (E:\JavaScript\CustomDCBot_V2\src\events\interactionCreate.js:17:21)
    at Client.<anonymous> (E:\JavaScript\CustomDCBot_V2\main.js:400:43)
    at Client.emit (node:events:394:28)
    at InteractionCreateAction.handle (E:\JavaScript\CustomDCBot_V2\node_modules\discord.js\src\client\actions\InteractionCreate.js:66:12)
    at Object.module.exports [as INTERACTION_CREATE] (E:\JavaScript\CustomDCBot_V2\node_modules\discord.js\src\client\websocket\handlers\INTERACTION_CREATE.js:4:36)
    at WebSocketManager.handlePacket (E:\JavaScript\CustomDCBot_V2\node_modules\discord.js\src\client\websocket\WebSocketManager.js:345:31)
    at WebSocketShard.onPacket (E:\JavaScript\CustomDCBot_V2\node_modules\discord.js\src\client\websocket\WebSocketShard.js:443:22)
    at WebSocketShard.onMessage (E:\JavaScript\CustomDCBot_V2\node_modules\discord.js\src\client\websocket\WebSocketShard.js:300:10)
    at WebSocket.onMessage (E:\JavaScript\CustomDCBot_V2\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (node:events:394:28)
```

Can anyone help me? Thanks

**Comment by jateute** [comment]
Ok. The error was, that I've edited some locals. Thank's for the help
